server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goodfriend_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: "your-256-bit-secret-key-here-1234567890abcdef"
    expiration: 86400000 # 24 hours